appName: shippingservice
appImage: bensassiahmed/shippingservice
appVersion: "1"
appReplicas: 2
containerPort: 50051
containerEnvVars:
- name: PORT
  value: "50051"

serviceType: ClusterIP
servicePort: 50051
